import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const player = '/player.html?game=nes-chise-yaosai';
async function start(page: Page) {
  await page.goto(player);
  await expect(page.locator('#launch')).toBeEnabled({ timeout: 70000 });
  await page.locator('#launch').click();
  await expect(page.locator('#play-status')).toHaveText('正在游玩');
  await expect.poll(() => page.evaluate(() => (window as any).EJS_emulator.gameManager.functions.getFrameNum())).toBeGreaterThan(50);
}
test('original ROM runs, controls work, pause stops frames and saves survive reload/cache clearing', async ({ page, request }, info) => {
  const errors: string[] = []; const external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith('http://127.0.0.1:')) external.push(request.url()); });
  const catalog = await (await request.get('/api/games')).json();
  expect(catalog.games[0].sha256).toBe('98ed6d10391cccef249ce45cd935eb6263163f727fbf2fc11adb8116aa49f31d');
  await page.goto('/'); await expect(page.locator('.game-card h3')).toHaveText('赤色要塞');
  await page.screenshot({ path: info.outputPath('library-desktop.png'), fullPage: true });
  await start(page);
  await page.keyboard.press('Enter', { delay: 150 });
  await page.waitForTimeout(1800);
  await page.keyboard.down('ArrowRight'); await page.keyboard.down('KeyX');
  await page.waitForTimeout(750); await page.keyboard.up('KeyX'); await page.keyboard.up('ArrowRight');
  const audioState = await page.evaluate(() => (window as any).EJS_emulator.Module.AL?.currentCtx?.audioCtx?.state);
  expect(audioState).toBe('running');
  await page.locator('#pause').click();
  const frame = await page.evaluate(() => (window as any).EJS_emulator.gameManager.functions.getFrameNum());
  await page.waitForTimeout(350);
  expect(await page.evaluate(() => (window as any).EJS_emulator.gameManager.functions.getFrameNum())).toBe(frame);
  await page.locator('#quick-save').click();
  await expect(page.locator('#toast')).toContainText('已保存到本机');
  const saved = await page.evaluate(async () => {
    const modulePath = '/src/storage.ts'; const storage = await import(modulePath);
    const records = await storage.listSaves();
    const bitmap = await createImageBitmap(records[0].screenshot); const canvas = document.createElement('canvas'); canvas.width = bitmap.width; canvas.height = bitmap.height;
    const ctx = canvas.getContext('2d')!; ctx.drawImage(bitmap, 0, 0); const pixels = ctx.getImageData(0, 0, canvas.width, canvas.height).data;
    let colored = 0; for (let i = 0; i < pixels.length; i += 4) if (pixels[i] + pixels[i+1] + pixels[i+2] > 30) colored++;
    return { hash: records[0].stateSha256, bytes: records[0].state.length, image: records[0].screenshot?.size, colored };
  });
  expect(saved.bytes).toBeGreaterThan(1000); expect(saved.image).toBeGreaterThan(100); expect(saved.colored).toBeGreaterThan(100);
  await page.locator('#resume').click(); await page.waitForTimeout(900); await page.locator('#pause').click();
  const laterState = await page.evaluate(async () => { const modulePath = '/src/storage.ts'; return (await import(modulePath)).sha256((window as any).EJS_emulator.gameManager.getState()); });
  expect(laterState).not.toBe(saved.hash);
  await page.locator('#quick-load').click();
  await expect(page.locator('#toast')).toContainText('已读取快速存档');
  const restoredState = await page.evaluate(async () => { const modulePath = '/src/storage.ts'; return (await import(modulePath)).sha256((window as any).EJS_emulator.gameManager.getState()); });
  expect(restoredState).toBe(saved.hash);
  await page.screenshot({ path: info.outputPath('player-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: '保存存档 01', exact: true }).click(); await expect(page.locator('#toast')).toContainText('存档 01已保存');
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: '导出快速存档', exact: true }).click();
  const exported = await download;
  expect(exported.suggestedFilename()).toBe('nes-chise-yaosai-quick.json');
  const backupPath = await exported.path(); if (!backupPath) throw new Error('Export missing');
  const backup = JSON.parse(await readFile(backupPath, 'utf8'));
  await page.locator('#save-file').setInputFiles({ name: 'wrong-version.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...backup, runtimeProfileId: 'other-core' })) });
  await expect(page.locator('#toast')).toContainText('不匹配');
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#save-file').setInputFiles(backupPath); await expect(page.locator('#toast')).toContainText('备份已导入');
  await page.goto('/#settings'); await page.locator('#clear-cache').click(); await expect(page.locator('#toast')).toContainText('存档已保留');
  await page.goto('/#saves'); await expect(page.locator('.save-row')).toHaveCount(2);
  await page.goto(player + '&slot=quick'); await expect(page.locator('#launch')).toBeEnabled({ timeout: 70000 });
  await page.locator('#launch').click(); await expect(page.locator('#toast')).toContainText('已读取快速存档');
  expect(errors).toEqual([]); expect(external).toEqual([]);
});
test('mobile sliding directions, simultaneous input, menu and rotation preserve the game', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 740 });
  await page.goto(player + '&source=wechat');
  await expect(page.locator('#launch')).toBeEnabled({ timeout: 70000 }); await page.locator('#launch').click();
  await expect(page.locator('.player-header')).toBeHidden();
  await page.locator('[data-input="start"]').click({ delay: 120 });
  await page.evaluate(() => {
    const e = (window as any).EJS_emulator;
    (window as any).inputEdges = [];
    (window as any).originalEmulator = e;
    const send = e.gameManager.simulateInput.bind(e.gameManager);
    e.gameManager.simulateInput = (player: number, key: number, down: number) => { (window as any).inputEdges.push([key, down]); send(player, key, down); };
  });
  const client = await page.context().newCDPSession(page);
  const pad = await page.locator('.dpad').boundingBox();
  const right = await page.locator('[data-input="right"]').boundingBox();
  const a = await page.locator('[data-input="a"]').boundingBox();
  const b = await page.locator('[data-input="b"]').boundingBox();
  if (!pad || !right || !a || !b) throw new Error('Controller missing');
  expect(pad.width).toBeGreaterThanOrEqual(144); expect(a.width).toBeGreaterThanOrEqual(64);
  const point = (box: { x: number; y: number; width: number; height: number }, id: number) => ({ x: box.x + box.width / 2, y: box.y + box.height / 2, id });
  await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point(right, 1), point(a, 2), point(b, 3)] });
  await expect(page.locator('[data-input="right"]')).toHaveClass(/pressed/); await expect(page.locator('[data-input="a"]')).toHaveClass(/pressed/);
  await expect(page.locator('[data-input="b"]')).toHaveClass(/pressed/);
  await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: pad.x + pad.width * .8, y: pad.y + pad.height * .2, id: 1 }, point(a, 2), point(b, 3)] });
  await expect(page.locator('[data-input="up"]')).toHaveClass(/pressed/);
  await expect(page.locator('[data-input="right"]')).toHaveClass(/pressed/);
  await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: pad.x + pad.width * .15, y: pad.y + pad.height * .5, id: 1 }, point(a, 2), point(b, 3)] });
  await expect(page.locator('[data-input="left"]')).toHaveClass(/pressed/);
  await expect(page.locator('[data-input="right"]')).not.toHaveClass(/pressed/);
  await expect(page.locator('[data-input="up"]')).not.toHaveClass(/pressed/);
  // A touch release must not release the same button still held on the keyboard.
  await page.keyboard.down('KeyX');
  await client.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] }); await expect(page.locator('[data-input="a"]')).toHaveClass(/pressed/);
  await page.keyboard.up('KeyX');
  await expect(page.locator('.pressed')).toHaveCount(0);
  const edges = await page.evaluate(() => (window as any).inputEdges);
  expect(edges).toContainEqual([4, 1]); expect(edges).toContainEqual([4, 0]); expect(edges).toContainEqual([6, 1]); expect(edges).toContainEqual([0, 1]);
  await page.screenshot({ path: info.outputPath('player-mobile.png'), fullPage: true });
  await page.locator('#pause').click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.locator('#control-size').selectOption('large'); await page.locator('#control-hand').selectOption('left');
  await page.locator('#volume').evaluate((node: HTMLInputElement) => { node.value = '35'; node.dispatchEvent(new Event('input', { bubbles: true })); });
  await page.screenshot({ path: info.outputPath('player-menu.png'), fullPage: true });
  await page.locator('#resume').click();
  expect((await page.locator('.dpad').boundingBox())!.x).toBeGreaterThan((await page.locator('.action-buttons').boundingBox())!.x);
  await page.keyboard.down('ArrowRight');
  await page.setViewportSize({ width: 844, height: 350 });
  await expect(page.locator('body')).toHaveAttribute('data-layout', 'landscape');
  await expect(page.locator('.pressed')).toHaveCount(0); await page.keyboard.up('ArrowRight');
  expect(await page.evaluate(() => (window as any).EJS_emulator === (window as any).originalEmulator)).toBe(true);
  await expect(page.locator('#play-status')).toHaveText('正在游玩');
  const frame = await page.evaluate(() => (window as any).EJS_emulator.gameManager.functions.getFrameNum());
  await expect.poll(() => page.evaluate(() => (window as any).EJS_emulator.gameManager.functions.getFrameNum())).toBeGreaterThan(frame + 10);
  await page.screenshot({ path: info.outputPath('player-landscape.png'), fullPage: true });
  await page.evaluate(() => window.dispatchEvent(new Event('blur'))); await expect(page.locator('#play-status')).toHaveText('已暂停');
  await expect(page.locator('#paused-frame')).toBeVisible();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.reload(); await expect(page.locator('#launch')).toBeEnabled({ timeout: 70000 }); await page.locator('#launch').click(); await page.locator('#pause').click();
  await expect(page.locator('#control-size')).toHaveValue('large'); await expect(page.locator('#control-hand')).toHaveValue('left'); await expect(page.locator('#volume')).toHaveValue('35');
});
test('small and large mobile viewports keep the 4:3 screen and all controls inside one viewport', async ({ page }) => {
  await page.goto(player + '&source=wechat');
  await expect(page.locator('#launch')).toBeEnabled({ timeout: 70000 }); await page.locator('#launch').click();
  for (const size of [{width:320,height:568},{width:375,height:600},{width:390,height:740},{width:430,height:820},{width:568,height:320},{width:667,height:300},{width:844,height:390},{width:932,height:360}]) {
    await page.setViewportSize(size);
    await expect.poll(() => page.evaluate(() => Math.round(document.body.getBoundingClientRect().height))).toBe(size.height);
    const bounds = await page.evaluate(() => {
      const screen = document.querySelector('.screen-stage')!.getBoundingClientRect();
      return { ratio: screen.width / screen.height, width: document.documentElement.scrollWidth, height: document.documentElement.scrollHeight, controls: [...document.querySelectorAll('.dpad, .action-buttons button, .system-buttons button, #pause')].map(el => { const r=el.getBoundingClientRect(); return {left:r.left,right:r.right,top:r.top,bottom:r.bottom}; }) };
    });
    expect(bounds.width, JSON.stringify(size)).toBe(size.width); expect(bounds.height, JSON.stringify(size)).toBe(size.height);
    expect(bounds.ratio).toBeCloseTo(4/3, 2);
    for (const box of bounds.controls) { expect(box.left).toBeGreaterThanOrEqual(0); expect(box.right).toBeLessThanOrEqual(size.width); expect(box.top).toBeGreaterThanOrEqual(0); expect(box.bottom).toBeLessThanOrEqual(size.height); }
  }
});
test('missing games, bad checksums and direct filesystem paths fail safely', async ({ page, request }) => {
  const game = await (await request.get('/api/games/nes-chise-yaosai')).json();
  expect((await request.get('/api/roms/nes-chise-yaosai?sha=wrong')).status()).toBe(409);
  expect((await request.post('/api/roms/nes-chise-yaosai')).status()).toBe(405);
  expect((await request.get('/api/roms/not-registered?sha=x')).status()).toBe(404);
  expect((await request.get('/@fs/Users/zebo/Downloads/nes/赤色要塞.nes')).status()).toBe(403);
  expect((await request.get('/runtime/emulatorjs/4.2.3/not-pinned.js')).status()).toBe(404);
  await page.goto('/player.html?game=missing'); await expect(page.locator('#load-message')).toContainText('找不到这张卡带'); await expect(page.locator('#retry')).toBeVisible();
  await page.route('**/api/roms/**', route => route.fulfill({ status: 200, body: Buffer.alloc(game.sizeBytes), contentType: 'application/octet-stream' }));
  await page.goto(player); await expect(page.locator('#load-message')).toContainText('ROM 校验失败');
  await page.unrouteAll();
  await page.route('**/data/cores/fceumm-legacy-wasm.data', route => route.fulfill({ status: 409, body: '{}' }));
  await page.goto(player); await expect(page.locator('#load-message')).toContainText('模拟器资源缺失或校验失败');
});
